# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: oracle_enhanced
  <% if defined?(JRUBY_VERSION) %>
  driver: oracle.jdbc.driver.OracleDriver
  url: jdbc:oracle:thin:@192.168.0.3:1521:WONDER
  <% else %>
  database: 192.168.0.3/wonder
  <% end %>
  username: consulta
  password: consulta



<%
  if defined?(JRUBY_VERSION) && defined?($servlet_context) && $servlet_context
    home = java.lang.System.getProperty 'jboss.home.dir'
    arquivo = home + '/server/default/conf/wmobile.yml'
    possui_conf = File.exist? arquivo
    if possui_conf
      require 'yaml'
      database = YAML.load_file(arquivo)['database']
      puts "Conexao com banco de dados direta via arquivo de configuracao: #{database['url']}"
    else
      puts "-"*50, "Conexao com banco de dados via JNDI - favor atualizar para novo formato", "*"*50
    end
  end
%>

production:
  adapter: oracle_enhanced
  <% if defined?(JRUBY_VERSION) %>
  driver: oracle.jdbc.driver.OracleDriver
  url: jdbc:oracle:thin:@192.168.0.3:1521:WONDER
  <% else %>
  database: 192.168.0.3/wonder
  <% end %>
  username: consulta
  password: consulta